// Generated by CoffeeScript 1.9.0
(function() {
  var chromeScript, reloadChrome, reloadSafari, reloadScript, run, safariScript, serializeArray, _;

  _ = require("lodash");

  run = require("run-applescript");

  serializeArray = function(arr) {
    if (!arr.length) {
      return "{}";
    }
    return "{\"" + (arr.join("\", \"")) + "\"}";
  };

  chromeScript = function(urls, js) {
    return "set hostLists to " + (serializeArray(urls)) + "\ntell application \"Google Chrome\"\n    set windowsList to windows as list\n    repeat with currWindow in windowsList\n        set tabsList to currWindow's tabs as list\n        repeat with currTab in tabsList\n            repeat with currentHost in hostLists\n                if currentHost is in currTab's URL then execute currTab javascript \"" + js + "\"\n            end repeat\n        end repeat\n    end repeat\nend tell";
  };

  safariScript = function(urls, js) {
    return "set hostLists to " + (serializeArray(urls)) + "\ntell application \"Safari\"\n    if (count of windows) is greater than 0 then\n        set windowsList to windows as list\n        repeat with currWindow in windowsList\n            set tabsList to currWindow's tabs as list\n            repeat with currTab in tabsList\n                repeat with currentHost in hostLists\n                    if currentHost is in currTab's URL then\n                        tell currTab to do JavaScript \"" + js + "\"\n                    end if\n                end repeat \n            end repeat\n        end repeat\n    end if\nend tell";
  };

  reloadScript = "location.reload();";

  reloadChrome = function(urls, js) {
    if (js == null) {
      js = reloadScript;
    }
    return run(chromeScript(urls, js), function(err, result) {});
  };

  reloadSafari = function(urls, js) {
    if (js == null) {
      js = reloadScript;
    }
    return run(safariScript(urls, js), function(err, result) {});
  };

  exports.reload = function(urls) {
    if (!_.isArray(urls)) {
      urls = [urls];
    }
    reloadChrome(urls);
    return reloadSafari(urls);
  };

}).call(this);
